# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Message tool for publishing to Eventarc Advanced."""

from __future__ import annotations

import base64
import binascii
import datetime
import json
import logging
from typing import Any
import uuid

import google.auth.credentials

try:
  from google.cloud import eventarc_publishing_v1  # type: ignore
except ImportError:
  eventarc_publishing_v1 = None

opentelemetry: Any = None
try:
  import opentelemetry
  import opentelemetry.propagate
except ImportError:
  opentelemetry = None

logger = logging.getLogger("google_adk." + __name__)

from . import _client as eventarc_client
from . import _config as config


async def publish_message(
    *,
    bus: str,
    type: str,
    source: str,
    credentials: google.auth.credentials.Credentials | None,
    settings: config.EventarcToolConfig,
    data: Any | None = None,
    is_base64_encoded: bool = False,
    include_tracing_extension: bool = False,
    datacontenttype: str | None = None,
    specversion: str = "1.0",
    subject: str | None = None,
    id: str | None = None,
    time: str | None = None,
    custom_attributes: dict[str, str] | None = None,
) -> dict[str, Any]:
  """Publishes a structured CloudEvent to a Google Cloud Eventarc Advanced Bus.

  This tool acts as a "fire-and-forget" publisher, allowing you to emit events
  to downstream subscribers in an Event-Driven Architecture.

  Args:
      bus: The fully-qualified GCP resource name of the Eventarc Advanced
        message bus. Must strictly match the format:
        projects/*/locations/*/messageBuses/*
      type: The CloudEvents type attribute. A value describing the type of event
        related to the originating occurrence (e.g.,
        'com.example.object.created').
      source: The CloudEvents source attribute. A URI-reference identifying the
        context in which an event happened.
      credentials: The Google Cloud credentials injected by the ADK wrapper.
      settings: The tool configuration injected by the ADK wrapper.
      data: Optional. The payload of the event. Can be a string, integer, float,
        boolean, dictionary, or list. If omitted, no payload is sent. If you
        need to send binary data, you MUST provide it here as a Base64 encoded
        string and set `is_base64_encoded=True`.
      is_base64_encoded: Optional. Set to True ONLY if the `data` parameter is a
        Base64 encoded string representing binary data (e.g., an image or file).
        The tool will decode it into raw bytes before publishing.
      include_tracing_extension: Optional. Set to True to automatically extract
        the current ADK agent's distributed tracing context (e.g., W3C
        traceparent) and inject it into the CloudEvent's extension attributes.
        Defaults to False.
      datacontenttype: Optional. The MIME type of the data (e.g.,
        'application/json', 'application/xml'). If omitted, the tool will
        automatically infer it based on the provided data type (e.g.,
        dicts/lists become application/json).
      specversion: Optional. The version of the CloudEvents specification which
        the event uses. Defaults to "1.0".
      subject: Optional. The subject of the event in the context of the event
        producer (often used for routing specific events).
      id: Optional. The unique ID of the event. If omitted, a UUIDv4 is
        auto-generated by the tool.
      time: Optional. The timestamp of the event in RFC 3339 format. If omitted,
        the current UTC time is auto-generated. Pass an explicit empty string ""
        to omit this attribute from the event entirely.
      custom_attributes: Optional. A dictionary of custom attributes. Keys must
        be lowercase alphanumeric.

  Returns:
      dict[str, Any]: Dictionary with the status (SUCCESS or ERROR), message_id
      (if successful), and error_details (if error).
  """
  if eventarc_publishing_v1 is None:
    return {
        "status": "ERROR",
        "error_details": "google-cloud-eventarc-publishing is not installed",
    }

  # Validation & Sanitization
  if not isinstance(type, str) or not type.strip():
    return {
        "status": "ERROR",
        "error_details": "type must be a non-empty string",
    }
  if not isinstance(source, str) or not source.strip():
    return {
        "status": "ERROR",
        "error_details": "source must be a non-empty string",
    }
  if id is not None and (not isinstance(id, str) or not id.strip()):
    return {
        "status": "ERROR",
        "error_details": "id, if provided, must be a non-empty string",
    }

  if is_base64_encoded:
    if not isinstance(data, str):
      return {
          "status": "ERROR",
          "error_details": (
              "data must be a string when is_base64_encoded is True"
          ),
      }
    try:
      data = base64.b64decode(data)
    except (TypeError, binascii.Error) as e:
      return {
          "status": "ERROR",
          "error_details": f"Invalid base64 string: {repr(e)}",
      }

  custom_attr = {}
  if custom_attributes is not None:
    if not isinstance(custom_attributes, dict):
      return {
          "status": "ERROR",
          "error_details": "custom_attributes must be a dict",
      }
    for k, v in custom_attributes.items():
      if not isinstance(k, str) or not k.isalnum() or not k.islower():
        return {
            "status": "ERROR",
            "error_details": (
                f"Invalid custom attribute key: {k}. Keys must be lowercase"
                " alphanumeric."
            ),
        }
      custom_attr[k] = str(v)

  time_attr = None
  if time is None:
    time_attr = datetime.datetime.now(datetime.timezone.utc).isoformat()
  elif time == "":
    time_attr = None
  else:
    if not isinstance(time, str):
      return {"status": "ERROR", "error_details": "time must be a string"}
    try:
      datetime.datetime.fromisoformat(time.replace("Z", "+00:00"))
      time_attr = time
    except ValueError:
      return {
          "status": "ERROR",
          "error_details": f"Invalid RFC 3339 time format: {time}",
      }

  if id is None:
    id = str(uuid.uuid4())

  # Data & Content-Type Introspection
  text_data = None
  binary_data = None

  if data is not None and data != "":
    if datacontenttype is None:
      if isinstance(data, (dict, list)):
        datacontenttype = "application/json"
      elif isinstance(data, str):
        datacontenttype = "text/plain"
      elif isinstance(data, bytes):
        datacontenttype = "application/octet-stream"
      else:
        datacontenttype = "application/json"

    if datacontenttype == "application/json":
      if not isinstance(data, (str, bytes)):
        try:
          text_data = json.dumps(data)
        except (TypeError, ValueError) as e:
          return {
              "status": "ERROR",
              "error_details": f"Failed to serialize data to JSON: {repr(e)}",
          }
      elif isinstance(data, bytes):
        binary_data = data
      else:
        text_data = data
    else:
      if isinstance(data, bytes):
        binary_data = data
      else:
        try:
          if isinstance(data, (dict, list)):
            text_data = json.dumps(data)
          else:
            text_data = str(data)
        except (TypeError, ValueError) as e:
          return {
              "status": "ERROR",
              "error_details": f"Failed to serialize data: {repr(e)}",
          }

  # Skip if datacontenttype explicitly equals ""
  if datacontenttype == "":
    datacontenttype = None

  if include_tracing_extension:
    if opentelemetry is not None:
      trace_carrier: dict[str, str] = {}
      opentelemetry.propagate.get_global_textmap().inject(trace_carrier)
      if "traceparent" in trace_carrier:
        custom_attr["traceparent"] = trace_carrier["traceparent"]
      if "tracestate" in trace_carrier:
        custom_attr["tracestate"] = trace_carrier["tracestate"]
    else:
      logger.warning(
          "Tracing extension requested but opentelemetry is not available."
      )

  if datacontenttype:
    custom_attr["datacontenttype"] = datacontenttype

  if time_attr:
    custom_attr["time"] = time_attr

  if subject:
    custom_attr["subject"] = subject

  # Prepare CloudEvent attributes
  attributes = {}
  for k, v in custom_attr.items():
    attributes[k] = (
        eventarc_publishing_v1.types.CloudEvent.CloudEventAttributeValue(
            ce_string=v
        )
    )

  # Construct Event
  event_kwargs: dict[str, Any] = {
      "id": id,
      "source": source,
      "type_": type,
      "spec_version": specversion,
      "attributes": attributes,
  }

  if text_data is not None:
    event_kwargs["text_data"] = text_data
  if binary_data is not None:
    event_kwargs["binary_data"] = binary_data

  event = eventarc_publishing_v1.types.CloudEvent(**event_kwargs)

  project_id = settings.project_id if settings else None

  try:
    client = await eventarc_client.get_publisher_client(
        credentials=credentials, project_id=project_id
    )

    request = eventarc_publishing_v1.types.PublishRequest(
        message_bus=bus, proto_message=event
    )
    timeout = settings.publish_timeout if settings else 15.0
    await client.publish(request=request, timeout=timeout)

    return {"status": "SUCCESS", "message_id": id}
  except Exception as e:
    await eventarc_client.remove_publisher_client(
        credentials=credentials, project_id=project_id
    )
    return {"status": "ERROR", "error_details": repr(e)}
