# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Upload ADK Docs to Vertex AI Search

on:
  # Runs once per day at 16:00 UTC
  schedule:
   - cron: '00 16 * * *'
  # Manual trigger for testing and fixing
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upload-adk-docs-to-vertex-ai-search:
    if: github.repository == 'google/adk-python'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clone adk-docs repository
        run: git clone https://github.com/google/adk-docs.git /tmp/adk-docs

      - name: Clone adk-python repository
        run: git clone https://github.com/google/adk-python.git /tmp/adk-python

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.ADK_GCP_SA_KEY }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-adk markdown google-cloud-storage google-cloud-discoveryengine

      - name: Run Answering Script
        env:
          GITHUB_TOKEN: ${{ secrets.ADK_TRIAGE_AGENT }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_LOCATION: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
          VERTEXAI_DATASTORE_ID: ${{ secrets.VERTEXAI_DATASTORE_ID }}
          GOOGLE_GENAI_USE_VERTEXAI: 1
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          ADK_DOCS_ROOT_PATH: /tmp/adk-docs
          ADK_PYTHON_ROOT_PATH: /tmp/adk-python
          PYTHONPATH: ${{ github.workspace }}/contributing/samples/adk_team
        run: python -m adk_answering_agent.upload_docs_to_vertex_ai_search
